### ISSUE TITLE
Enable flow-type eslint plugin rules

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#29]
# Goal
Make the codebase more consistent with clear standards.

# Overview
Original issue (#18)

Flow-types helps to reason about the code and maintain a stable API. Unfortunately, some files don't have flow, and the types don't match best-established practices, like avoiding `any` and `*Type` type names.

# Acceptance Criteria

These are the sequence for how these changes should be applied. The only additional eslint rules to run on are listed below.

- [x] Add [eslint-flowtype plugin](https://github.com/gajus/eslint-plugin-flowtype)
  * Add flowtype rules, disabled. #32 
- [x] Add `validation` script to travis-ci #32 
- [x] Turn on rule [type-id-match](https://github.com/gajus/eslint-plugin-flowtype#type-id-match), fix type names everywhere
- [x] Turn on rule [require-valid-file-annotation](https://github.com/gajus/eslint-plugin-flowtype#require-valid-file-annotation) and add flow to all files.
- [x] Add `npm run flow` checks to `validation` script/travis-ci, fix errors.

**Comment by ForsakenHarmony** [comment]
Are all the disabled rules and warnings in the `.eslintrc` intentional?

**Comment by ballercat** [comment]
I didn't have much use for them when it was just me working on the code. I'll have to re-enable most of these as part of the Issue.

**Comment by ForsakenHarmony** [comment]
then why not just disable eslint?

**Comment by ballercat** [comment]
It's important to me that the code remains as easy as possible to maintain, especially as the project grows. I'd like to get more people involved improving the codebase as well, not having a standard style would make that difficult. 

The results of me being lazy about enabling the rules are inconsistencies across the codebase now. How can I ask others to maintain quality if I can't follow the rules myself? And If I do get enough people to contribute, one of the worst things that could happen are arguments over code-style, which I'd like to avoid.

**Comment by ForsakenHarmony** [comment]
No I'm asking why you used eslint before if you disable all those rules

**Comment by ballercat** [comment]
Oh, sure. 

If you take a look at the currently enabled config, it's already pretty useful; it just doesn't enforce a few style rules I have done out of habit. It helped me catch silly bugs(undefined variables etc.,), and keep stuff like console.logs and debugger statements out of builds.

**Comment by ballercat** [comment]
Going to punt on the type naming rule. Maybe will be done at a later point.
