### ISSUE TITLE
Memory, Arrays, sizeof

### ISSUE THREAD

**Issue by ballercat** [ballercat/walt#8]
# Goal
Provide the ability to declare and use non-trivial data stored in memory.

# TODO

- [x] `Memory` built-in type and parser
- [x] Custom user built-in types
- [x] Array syntax, parser, generator
- [x] `sizeof` method

# Overview

### Memory

Memory import and declaration is explicit.

### `sizeof`
`sizeof` function is compiled to a static size of a type/array in **bytes**

```js
sizeof(i32); // 4
sizeof(i64); // 8
```

### Arrays
Flow array shorthand should be supported

```js
let foo: i32[] = 0
```

```js
import { memcpy: MemCopyType } from 'utils';

type MemCopyType = (i32, i32, i32) => i32;

function test(): void {
   const a: i32[] =  0;
   const b: i32[] = 100;
 
   a[0] = 1;
   a[1] = 2;
   a[2] = 3;
   // memcpy like function can be employed
   memcpy(b, a, sizeof(a));
}
```
